# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'XKCommonTools' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for XKCommonTools
    pod 'SVProgressHUD'
    pod 'Masonry'
    pod 'YYCategories'

  target 'XKCommonToolsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'XKCommonToolsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
